// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/pivotalservices/cfbackup"
)

type FakeDirectorCreator struct {
	Stub        func(ip, username, password string, port int) (cfbackup.Bosh, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		ip       string
		username string
		password string
		port     int
	}
	returns struct {
		result1 cfbackup.Bosh
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 cfbackup.Bosh
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDirectorCreator) Spy(ip string, username string, password string, port int) (cfbackup.Bosh, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		ip       string
		username string
		password string
		port     int
	}{ip, username, password, port})
	fake.recordInvocation("DirectorCreator", []interface{}{ip, username, password, port})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(ip, username, password, port)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.returns.result1, fake.returns.result2
}

func (fake *FakeDirectorCreator) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeDirectorCreator) ArgsForCall(i int) (string, string, string, int) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].ip, fake.argsForCall[i].username, fake.argsForCall[i].password, fake.argsForCall[i].port
}

func (fake *FakeDirectorCreator) Returns(result1 cfbackup.Bosh, result2 error) {
	fake.Stub = nil
	fake.returns = struct {
		result1 cfbackup.Bosh
		result2 error
	}{result1, result2}
}

func (fake *FakeDirectorCreator) ReturnsOnCall(i int, result1 cfbackup.Bosh, result2 error) {
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 cfbackup.Bosh
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 cfbackup.Bosh
		result2 error
	}{result1, result2}
}

func (fake *FakeDirectorCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.invocations
}

func (fake *FakeDirectorCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cfbackup.DirectorCreator = new(FakeDirectorCreator).Spy
